module.exports = {
  config: {
    name: "truth",
    aliases: [],
    version: "1.0",
    author: "Nerob",
    countDown: 5,
    role: 0,
    shortDescription: "Truth game",
    longDescription: "Send a random truth question in banglish",
    category: "game",
    guide: {
      en: "{pn}",
    },
  },

  onStart: async function ({ message, event }) {
    const senderID = event.senderID;
    const mentionTag = `@${senderID}`;

  const truths = [
  `Tui last kiss kake disos? 💋 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kono bondobi ke line disos? 😏 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Bondhur gf/bf ke kokhono like korchos? 🤫 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Last time kokhono jealous hoisili ar kar jonno? 💢 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor phone e ekhn most embarrassing pic konta? 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki aj porjonto kono cheating korchos kono relation e? 💔 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kono onek older man/woman ke like korchos? 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor life e first proposal kotobar disos? 💌 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kiss er time pet e awaj dise? 😂 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor gopon friend er naam bol 🕵️‍♂️ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Ekta embarrassing dating story bol 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui jodi 1 rat kono famous celeb er sathe thakte parti ke nitis? 🌃 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor first romantic dream k niye chilo? 💭 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono kono friend er status dekhay nijeke lonely feel korchos? 😢 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor first porn search ki chilo? 🔞 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kichu fake kore nijeke innocent dekhasos? 😇 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono ma ke vule bondobi'r naam bole felse? 😬 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Last baar tumi nijeke mirror e dekhe flirt korchos? 😍 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono real life e dirty msg send kore bhul chat e geche? 💬 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki kokhono pretend korchos je boro manush? 🕴️ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono breakup er por pretend korchos je valo aso? 😌 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kono teacher ke crush korchos? 👩‍🏫 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono tmr bondhur date crash korchos? 🧨 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki ex er shathe abar contact e ashcho? 🔙 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono bondhur sathe 1 bed e ghumaiya kichu feel korsos? 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui janiye kono friend er relationship break korchos? 💔 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki best friend er crush ke propose korta chas? 😬 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki kono fake fb id diye kono ke troll korsos? 🤖 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor life e first heartbreak er karon ki chilo? 💔 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kono bar concert e prem korchos? 🎤 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui friend der sathe kono cheating korchos j era janeo na? 🤐 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono phone er password girlfriend/boyfriend theke lukiye rakhchos? 🔒 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono friend der moddhe kono ekjon ke special feel korchos? 💕 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki kokhono bolchos "I love you" just time pass er jonno? ⏳ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono class er samne girchos embarrass hoye? 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono ekta friend er pichone gossip korsos? 🗣️ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kono celeb er pic e kiss diye screen cleaner banaiya rekhechis? 📱 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui best friend er love letter porchos jante giya? 💌 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kono friend ke miss korleo contact korona? 😞 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono boro hoye celeb hobar shopno dekhechis? 🌟 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kharap report card lukay falsos? 📉 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui je ekta romantic msg copy paste kore onek jon ke disos? 😅 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui life e kokhono "I’m not ready" excuse use korsos break up er jonno? 🥲 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono friend er shathe acting korsos j happy aso, but asole na? 😔 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ekbar accidental nud3 dekhe freak out korsos? 😱 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ekta bar phone theke shudhu ekjon er pic save rekhe chill korsos? 📁 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ekta bondhur birthday bhule gelo on purpose? 🎂 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono chinta korsos j best friend ke propose korbi? 🤭 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor first online dating experience kemon chilo? 💻 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono kono song er lyrics bhule awkward moment face korsos? 🎶 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono kono dress pora niye nijeke overconfident feel korsos? 👗 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono best friend er sathe secret place e giyechili? 🕶️ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui life e kokhono kiss hoyeche friend er dare e? 💋 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ekta friend er crush e crush kheye porchos? 😵 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ekta bondhur shathe kono awkward hug experience korchos? 🤗 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono bhabi chinta korsos j tor friend actually tor ex er sathe ghurte geche? 🧐 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kono friend er bondhu ke dekhe instantly like korsos? ⚡ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono nighty pora ke dekhle excited hoisili? 😏 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kon friend ke secretly dirty vabe dekhosh? 🤤 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono kono porn video dekhar por nijeke question korsos? 🫣 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor first dirty msg kar sathe chilo? 📲 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kono friend er body part e beshi attention disos? 🍑🍒 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono bistar e kichu weird feel korsos? 🛏️ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki ekta sex dream dekhe ghume theke uthe porechili? 🌙 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono real life e kono dirty fantasy try korar iccha chilo? 🔥 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kon celeb er sathe ekta raater fantasy koros? 🛌 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kiss er pore onno kichu try korar cheshta korsos? 💋➡️😈 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki sexting kore kono screenshot rekhechis? 📸 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono GF/BF'r body smell niye addicted hoisili? 👃 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor first erotic thought kokhon asche mone ase? 🧠 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono ekla thakte giye "kaaj" kore fellis? ✋😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono dirty msg friend der modhhe bhul group e pathaiya disos? 💬🔥 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor shobcheye hottest fantasy ki? 😈 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor kon friend sexy dress porle chokh tule takaiya thakis? 👀 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kono photo dekhe night e ghume para jae nai? 😅 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ki first kiss e tongue use korsos? 👅 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kono bestfriend er sathe dirty thoughts ashchilo? 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF ke kokhono secretly pic tulchos nude moto? 📷 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF er kon gesture e instantly weak hoye jaos? 💓 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor phone e ki kono private folder ase? 🙈 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono kono random stranger ke hot mone korsos? 🔥 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF er ki part beshi pashondo koros? 😌 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono chhotto age sexy dress try korsos secretly? 👗 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui school e kono locker e secret note chhere aschos? 📝 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui choto belay kokhono pillow ke GF/BF mone korchos? 😂 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF er shathe first time physical hobar por ki feel korsos? 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor kono memory ase jeta mone porlei blushing hoye jaos? 😊 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono "I’m home alone" msg diye kichu expect korsos? 🏠 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono kono date e giye overly touchy hoisili? 🙃 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor sathe ke first time “closer” hobar cheshta korsilo? 😮‍💨 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono mirror e nijeke "attractive" bole flirt korsos? 😏 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor sexiest voice konta mone hoye? Male or female? 🔊 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `GF/BF jokhon neck touch kore ki feel hoye? 😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Choto belay kon dress porle nijeke sexy mone hoito? 👶➡️🔥 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono bed e moaning practice korsos? 😶‍🌫️ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono GF/BF'r pic dekhe kiss disos phone e? 😘 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF ke kokhono secretly smell disos just feel er jonno? 🫣 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono fake scenario niye fantasize korsos? 🎭 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF er kono body part niye poem likhechis? 📝❤️ (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono sex er dike giye pause korsos bhoy e? 😬 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ekta date e kisu chaileo bolte paroni — ki chilo? 🤐 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `GF/BF er sathe kono weird sound hoisilo kiss time? 😅 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor body’r kon part sensitive? 🫢 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono online dirty call try korsos? 📞🔥 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kono friend er voice sexy mone koros secretly? 🫣 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF ke kokhono “just hug” theke beshi chao ni? 🫂➡️😳 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui ekbar sexy message likhe send dite giye delete korsos? 📲 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui GF/BF er choker niche kiss korte beshi like koros? 😚 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tor friend circle e ke sexy lagay but tui bolos na kokhono? 👀 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui kokhono ekta kiss “accidentally” bar korchos? 😏 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Tui jodi ek din full bold hote partis GF/BF sathe, ki kortis? 🔥 (na bolle gay/lesbo🥰 ${mentionTag})`,
  `Kokhono GF/BF ke dirty msg pathaiya tar reply ta screenshot kore save korsos? 📲🔥 (na bolle gay/lesbo🥰 ${mentionTag})`
    ];

    const randomTruth = truths[Math.floor(Math.random() * truths.length)];
    message.reply(randomTruth);
  }
};
